<?php

declare (strict_types=1);
/**
 * SCSSPHP
 *
 * @copyright 2012-2020 Leaf Corcoran
 *
 * @license http://opensource.org/licenses/MIT MIT
 *
 * @link http://scssphp.github.io/scssphp
 */
namespace Scss_Php\Scss_Php\Ast;

use Source_Span\File_Span;
/**
 * An {@see AstNode} that just exposes a single span generated by a callback.
 *
 * @internal
 */
final class Fake_Ast_Node implements Ast_Node
{
    /**
     * @var \Closure(): FileSpan
     */
    private readonly \Closure $callback;
    /**
     * @param callable(): FileSpan $callback
     */
    public function __construct(callable $callback)
    {
        $this->callback = $callback(...);
    }
    public function get_span(): File_Span
    {
        return ($this->callback)();
    }
    public function __toString(): string
    {
        return '';
    }
}